version: '3.3'
volumes:
  pgdata2: {}
  pgback: {}
  pgadmin2:
services:
   
  postgres:
    container_name: docker_postgres2      
    image: postgres:14
    restart: always
    environment:
            POSTGRES_USER: superadmin
            POSTGRES_Pversion: '3.3'
volumes:
  pgdata2: {}
  pgback: {}
  pgadmin2:
services:

  postgres:
    container_name: docker_postgres2
    image: postgres:14
    restart: always
    environment:
            POSTGRES_USER: superadmin
            POSTGRES_PASSWORD: sadm
            POSTGRES_DB: sup_db
            PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
          - "./pgdata2:/var/lib/postgresql/data/pgdata"
            # - "./pgdata:/docker-entrypoint-initdb.d"
            #- "./test_db.sql:/docker-entrypoint-initdb.d/test_db.sql"
            # - "./data.sql:docker-entrypoint-initdb.d/data.sql"
            #- "./pgback"
    ports:
          - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:5.5
    environment:
           PGADMIN_DEFAULT_EMAIL: ars@ars.com
           PGADMIN_DEFAULT_PASSWORD: pgadmin
           PGADMIN_LISTEN_PORT: 8080
    volumes:
         - "./pgadmin2:/root/.pgadmin"
    ports:
            - "8080:8080"
    restart: always
ASSWORD: sadm
            POSTGRES_DB: sup_db
            PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
          - "./pgdata2:/var/lib/postgresql/data/pgdata"
            # - "./pgdata:/docker-entrypoint-initdb.d"
            #- "./test_db.sql:/docker-entrypoint-initdb.d/test_db.sql"
            # - "./data.sql:docker-entrypoint-initdb.d/data.sql"  
            #- "./pgback"
    ports:
          - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:5.5
    environment:
           PGADMIN_DEFAULT_EMAIL: ars@ars.com
           PGADMIN_DEFAULT_PASSWORD: pgadmin
           PGADMIN_LISTEN_PORT: 8080
    volumes:
         - "./pgadmin2:/root/.pgadmin"
    ports:
            - "8080:8080"
    restart: always
 
    #      cpus: '0.5'
    #      memory: 1G
    #networks:
    #  - postgres
    #networks:
    #  postgres:
    #driver: bridge

