version: '3.3'
volumes:
  msqldata: {}
  msqlback:
          
  mysql:
          # external: true       
  pgadmin:
services:
  dbmysql:
    build: .
    container_name: doc_mysql_db
    image: mysql:8
    #command: --default-autentification-plugin=mysql_native_password
    restart: always
    ports: 
        - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: madm    
      MYSQL_DATABASE: msql_db
      MYSQL_USER: madm
    volumes:
            #    - "./mysql:/etc/mysql"
      - "./msqlback:/mnt/msqlback" 
      - "./msqldata:/var/lib/mysql"  
      - "./mydoc.sql:/docker-entrypoint-initdb.d/mydoc.sql"  
  dbeaver:
    container_name: doc_eaver        
    image: dbeaver/cloudbeaver:latest
    ports:
      - "8081:8978"
